---
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: 255.255.255.0
  checked: true
- !ruby/hash:BSON::Document
  value: 255.255.255.128
  checked: false
- !ruby/hash:BSON::Document
  value: 255.255.255.240
  checked: false
