---
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: Primera
  checked: false
- !ruby/hash:BSON::Document
  value: Segunda
  checked: true
- !ruby/hash:BSON::Document
  value: Tercera
  checked: false
